#!/bin/sh

if [ -z "$1" ]; then
	echo "$0: usage: $0 [<ffmpeg_args>]" >&2
	exit 1
fi

exec ffmpeg \
	-f pulse \
	-i ${AUDIO_DEVICE:-default} -ac 2 \
	-c:a pcm_s16le \
	\
	-f x11grab \
	-video_size 1920x1140 -framerate 20 \
	-i :0.0+0,60 \
	-c:v libx264 -qp 0 -preset ultrafast \
	-strict -2 \
	\
	-ac 1 \
	-y \
	"$@"
